// angular-app/src/app/home/home.component.ts
import { Component } from '@angular/core';
import axios from 'axios';

interface Country {
  capital: string;
  language: string | string[];
  population: number;
  name: string;
  region: string;
  flag: string;
  map: string;
}

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  search: any = '';
  country: any; // You should have a proper type for country, replace 'any' with the appropriate type.
  loading: boolean = false;
  error: boolean = false;

  isObject(value: any): boolean {
    return typeof value === 'object';
  }

  getLanguageValues(languageObj: any): string[] {
    return Object.values(languageObj);
  }

  async submitCountry() {
    this.country = '';
    this.loading = true;
    this.error = false;
    try {
      const res = await axios.get(
        `https://restcountries.com/v3.1/name/${this.search}`
      );

      this.country = {
        capital: res.data[0]?.capital,
        language: res.data[0]?.languages,
        population: res.data[0]?.population,
        name: res.data[0]?.name?.common,
        region: res.data[0]?.region,
        flag: res.data[0]?.flags?.png,
        map: res.data[0]?.maps?.googleMaps,
      };
      console.log(this.country);
    } catch (error) {
      console.log(error);
      this.error = true;
    }
    this.loading = false;
  }
}

<section class="flex justify-center items-center h-[100vh] bg-[#C70039]">
  <article
    class="flex flex-col bg-white w-[90%] max-w-[1000px] rounded-md shadow-2xl"
  >
    <div class="flex flex-col gap-12 min-h-[80vh]">
      <div
        class="flex justify-center items-center text-[#C70039] text-2xl font-bold mt-6 md:text-4xl lg:text-5xl"
      >
        <h1>Countries of the world</h1>
      </div>
      <div class="flex justify-center">
        <form (ngSubmit)="submitCountry()">
          <input
            placeholder="Search..."
            class="pl-2 h-[4vh] w-[100%] border border-1 border-black rounded-md"
            [(ngModel)]="search"
            name="search"
          />
        </form>
      </div>
      <div *ngIf="error" class="flex justify-center text-red-600">
        Invalid input. Try again
      </div>
      <ng-container *ngIf="country">
        <div class="flex justify-center">
          <img [src]="country.flag" alt="flag" />
        </div>
        <div class="flex justify-center text-[#C70039] text-2xl font-bold">
          <h2 class="w-[220px]">{{ country.name }}</h2>
        </div>
        <div class="flex flex-col gap-4 justify-center items-center font-bold">
          <p class="bg-[#FFE5B4] w-[220px] rounded-md">
            Capital: {{ country.capital }}
          </p>

          <ng-container
            *ngIf="
              country.language && isObject(country.language);
              else stringLanguage
            "
          >
            <p class="bg-[#FFE5B4] w-[220px] rounded-md">
              Language:
              {{ getLanguageValues(country.language).join(", ") }}
            </p>
          </ng-container>
          <ng-template #stringLanguage>
            <p class="bg-[#FFE5B4] w-[220px] rounded-md">
              Language: {{ country.language }}
            </p>
          </ng-template>

          <p class="bg-[#FFE5B4] w-[220px] rounded-md">
            Population: {{ country.population }}
          </p>
          <p class="bg-[#FFE5B4] w-[220px] rounded-md">
            Currency: {{ country.region }}
          </p>
        </div>
        <div class="flex justify-center mb-3">
          <a
            href="{{ country.map }}"
            class="p-3 bg-[#FF4177] text-white font-medium rounded-md"
          >
            See on Google Maps
          </a>
        </div>
      </ng-container>
      <div class="flex justify-center" *ngIf="loading">
        <p>Loading...</p>
      </div>
    </div>
  </article>
</section>

// react-app/src/pages/Home.js
import { Oval } from "react-loading-icons";

const Home = ({
  search,
  setSearch,
  submitCountry,
  country,
  loading,
  error,
}) => {
  return (
    <section className="flex justify-center items-center h-[100vh] bg-[#C70039]">
      <article className="flex flex-col bg-white w-[90%] max-w-[1000px] rounded-md shadow-2xl">
        <div className="flex flex-col gap-8 min-h-[80vh]">
          <div className=" flex justify-center items-center text-[#C70039] text-2xl font-bold mt-6 md:text-4xl lg:text-5xl">
            <h1>Countries of the world</h1>
          </div>
          <div className="flex justify-center">
            <form onSubmit={submitCountry}>
              <input
                placeholder="Search..."
                className="pl-2 h-[4vh] w-[100%] border border-1 border-black rounded-md"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </form>
          </div>
          {error && (
            <div className="flex justify-center text-red-600">
              Invalid input. Try again
            </div>
          )}

          {country ? (
            <>
              <div className="flex justify-center">
                <img src={country.flag} alt="flag" />
              </div>
              <div className="flex justify-center text-[#C70039] text-2xl font-bold ">
                <h2 className="w-[200px]">{country.name}</h2>
              </div>
              <div className="flex flex-col gap-4 justify-center items-center font-bold">
                <p className=" bg-[#FFE5B4] w-[200px] rounded-md">
                  Capital: {Object.values(country.capital).join(", ")}
                </p>

                {country.language && typeof country.language === "object" ? (
                  <p className=" bg-[#FFE5B4] w-[200px] rounded-md">
                    Language: {Object.values(country.language).join(", ")}
                  </p>
                ) : (
                  <p className=" bg-[#FFE5B4] w-[200px] rounded-md">
                    Language: {country.language}
                  </p>
                )}
                <p className=" bg-[#FFE5B4] w-[200px] rounded-md">
                  Population: {country.population}
                </p>
                <p className=" bg-[#FFE5B4] w-[200px] rounded-md">
                  Currency: {country.region}
                </p>
              </div>
              <div className="flex justify-center mb-3">
                <a
                  href={country.map}
                  className="p-3 bg-[#FF4177] text-white font-medium rounded-md"
                >
                  See on Google Maps
                </a>
              </div>
            </>
          ) : (
            loading && (
              <div className="flex justify-center">
                <Oval stroke="black" strokeOpacity={0.5} fill="white" />
              </div>
            )
          )}
        </div>
      </article>
    </section>
  );
};

export default Home;
